version: '3.8'
services:
  app:
    image: "otr-api-dev:latest"
    ports:
      - "3700:8080"
    env_file:
      - app.env
    depends_on:
      - db
      # - cache
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - collector
      - clickhouse
    environment:
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  db:
    container_name: db
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - db.env
    ports:
      - "5432:5432"
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    ports:
      - "9187:9187"
    env_file:
      - ./postgres_exporter.env
    links:
      - db
      - prometheus
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: collector
    command: [ "--config=/etc/collector.yml" ]
    ports:
      - "4317:4317"
    volumes:
      - ./otel-collector-config.yml:/etc/collector.yml:ro
    depends_on:
      - clickhouse
  clickhouse:
    image: clickhouse/clickhouse-server:head
    container_name: clickhouse
    ports:
      - "9000:9000"
      - "8143:8143"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
volumes:
  db_data:
